### PR TITLE
Modify to allow a mix of numerical and categorical data

### PR DESCRIPTION
**Pull request by EmergentOrder**

### CODE REVIEW

**Comment by zygmuntz** [comment]
Some things need to straightened up:
1. make sure you use tabs for indentation
2. what if _item_ contains spaces or "|" or ":"?
3. one can use shorthand notation: instead of "item:1", just "item"

**Comment by EmergentOrder** [comment]
Good suggestions, made those changes.

**Comment by zygmuntz** [comment]
Have you tested it? Does it work?

**Comment by EmergentOrder** [comment]
Yeah, I used it to generate VW formatted training and test data in order to make submissions for these two Driven Data competitions: 
http://www.drivendata.org/competitions/7/
http://www.drivendata.org/competitions/6/

**Comment by zygmuntz** [comment]
OK, merging then.

**Comment by EmergentOrder** [comment]
thanks, and thank you for providing this tool!

**Pull request merged**
