### PR TITLE
Dealt with the case of missing response variables. Also added shuffle.py from original phraug

### PR DESCRIPTION
**Pull request by alexchao56**
Handled the case when the response variable is missing or an empty string.

Added the shuffle.py script from the original phraug so that phraug2 can support shuffling.

### CODE REVIEW

**Comment by zygmuntz** [comment]
Adding shuffle.py is by all means welcome, just update handling of command line arguments, like in other scripts - that's the difference between phraug and phraug2.

Where would `ValueError` in `construct_line()` come from?

**Comment by alexchao56** [comment]
The error arises when there are missing Target values in the data. Is there
a way to skip over them other than using a try except? Otherwise I would
have to preprocess the data to remove those rows in order to run
csv2libsvm.py

Thanks for the reply.

Alex

**Comment by zygmuntz** [comment]
I see, added the try/except block skipping malformed lines and printing a warning.

**Comment by alexchao56** [comment]
Great! You can feel free to close the pull request if you'd like.

**Comment by alexchao56** [comment]
Do you need to add `continue` after the Except clause to go to the next
iteration of the for loop? I had that in my original pull request so that
it will not only catch that error but go to the next iteration.

Thanks,
Alex

**Comment by zygmuntz** [comment]
Nope, because writing is in the `try` block.

**Pull request closed without merging**
